const sampleData = {
  products: [
    {
      name: "پیراهن مردانه کشی پولو",
      slug: "polo-sporting-stretch-shirt",
      category: "پیراهن رسمی مردانه",
      description: "استایل کلاسیک پولو با راحتی مدرن",
      images: [
        "/images/sample-products/p1-1.jpg",
        "/images/sample-products/p1-2.jpg",
      ],
      price: 1850000,
      brand: "Polo",
      rating: 4.5,
      numReviews: 12,
      stock: 5,
      isFeatured: true,
      banner: "banner-1.jpg",
    },
    {
      name: "پیراهن آستین بلند Brooks Brothers",
      slug: "brooks-brothers-long-sleeved-shirt",
      category: "پیراهن رسمی مردانه",
      description: "استایلی ماندگار و راحتی بی‌نظیر",
      images: [
        "/images/sample-products/p2-1.jpg",
        "/images/sample-products/p2-2.jpg",
      ],
      price: 2500000,
      brand: "Brooks Brothers",
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: "banner-2.jpg",
    },
    {
      name: "پیراهن کلاسیک Tommy Hilfiger",
      slug: "tommy-hilfiger-classic-fit-dress-shirt",
      category: "پیراهن رسمی مردانه",
      description: "ترکیبی عالی از زیبایی و راحتی",
      images: [
        "/images/sample-products/p3-1.jpg",
        "/images/sample-products/p3-2.jpg",
      ],
      price: 3200000,
      brand: "Tommy Hilfiger",
      rating: 4.9,
      numReviews: 25,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: "پیراهن اسلیم فیت Calvin Klein",
      slug: "calvin-klein-slim-fit-stretch-shirt",
      category: "پیراهن رسمی مردانه",
      description: "طراحی مدرن با پارچه کشی و انعطاف‌پذیر",
      images: [
        "/images/sample-products/p4-1.jpg",
        "/images/sample-products/p4-2.jpg",
      ],
      price: 1500000,
      brand: "Calvin Klein",
      rating: 3.6,
      numReviews: 5,
      stock: 15,
      isFeatured: false,
      banner: null,
    },
    {
      name: "پیراهن آکسفورد رالف لورن",
      slug: "polo-ralph-lauren-oxford-shirt",
      category: "پیراهن رسمی مردانه",
      description: "طراحی نمادین پولو با پارچه آکسفورد باکیفیت",
      images: [
        "/images/sample-products/p5-1.jpg",
        "/images/sample-products/p5-2.jpg",
      ],
      price: 2800000,
      brand: "Polo",
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: "هودی کلاسیک صورتی پولو",
      slug: "polo-classic-pink-hoodie",
      category: "هودی و سویشرت مردانه",
      description: "نرم، شیک و عالی برای روزهای کژوال",
      images: [
        "/images/sample-products/p6-1.jpg",
        "/images/sample-products/p6-2.jpg",
      ],
      price: 3500000,
      brand: "Polo",
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;
