import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const VazirSans = Vazirmatn({
  variable: "--font-vazir-sans",
  subsets: ["arabic"],
  display: "swap",
});

const EstedadSans = localFont({
  src: "../../public/fonts/Estedad-FD.woff2",
  variable: "--font-estedad-fd",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${VazirSans.variable} ${EstedadSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
